"""Template desain siap pakai.

Untuk menambah template: tambahkan satu entri di TEMPLATES memakai fungsi
pembantu (H, P, B, IMG, GAL, LST, INP, CARD, DIV, SPC, NAV, FOOT, BAR).
"""
import copy
import uuid

from config import ELEMENT_DEFAULTS, ELEMENT_STYLE_DEFAULTS
from design import default_design, theme_of
from styles import ensure_element_style


def mk(el_type, **props):
    el = {"type": el_type}
    el.update(copy.deepcopy(ELEMENT_DEFAULTS[el_type]))
    el["visual_style"] = copy.deepcopy(ELEMENT_STYLE_DEFAULTS)
    el.update(props)
    ensure_element_style(el)
    return el


def pic(seed, w=800, h=400):
    return f"https://picsum.photos/seed/{seed}/{w}/{h}"


def H(text, size=32, align="left"):
    return mk("heading", text=text, size=size, align=align)


def P(text, align="left"):
    return mk("text", text=text, align=align)


def B(text, link="", align="left"):
    return mk("button", text=text, link=link, align=align)


def IMG(seed, alt, radius=12, w=800, h=400):
    return mk("image", url=pic(seed, w, h), alt=alt, radius=radius)


def GAL(seeds, cols=3, radius=8):
    return mk("gallery", urls="\n".join(pic(s, 400, 300) for s in seeds), columns=cols, radius=radius)


def LST(items, style="bullet"):
    return mk("list", items="\n".join(items), style=style)


def INP(label, placeholder="", kind="text"):
    return mk("input", label=label, placeholder=placeholder, kind=kind)


def CARD(title, text):
    return mk("card", title=title, text=text)


def DIV():
    return mk("divider")


def SPC(height=24):
    return mk("spacer", height=height)


def NAV(brand, links):
    return mk("navbar", brand=brand, links="\n".join(f"{a}|{b}" for a, b in links))


def FOOT(text):
    return mk("footer", text=text)


def BAR(el_type, **props):
    return mk(el_type, **props)


TEMPLATES = {
    "landing_produk": {
        "name": "Landing page produk",
        "category": "Bisnis",
        "desc": "Halaman promosi satu layar: hero, tiga fitur, dan ajakan mendaftar.",
        "title": "Nusa Keuangan",
        "theme": theme_of("#4f46e5", "#ffffff", "#111827", width=760),
        "pages": [{"name": "Beranda", "elements": [
            NAV("Nusa Keuangan", [("Fitur", "#"), ("Harga", "#"), ("Kontak", "#")]),
            SPC(16),
            H("Kelola uang harian dengan lebih tenang", 40, "center"),
            P("Catat pemasukan dan pengeluaran, lihat laporan otomatis, semuanya dari satu aplikasi.", "center"),
            B("Coba gratis", "#", "center"),
            IMG("finance", "Tampilan aplikasi"),
            H("Fitur utama", 28),
            CARD("Catatan cepat", "Tambah transaksi dalam hitungan detik, tanpa formulir panjang."),
            CARD("Laporan otomatis", "Ringkasan mingguan dan bulanan tanpa perlu spreadsheet."),
            CARD("Data aman", "Semua catatan tersimpan terenkripsi di perangkatmu."),
            DIV(),
            H("Siap mulai?", 28, "center"),
            B("Unduh sekarang", "#", "center"),
            FOOT("© 2026 Nusa Keuangan"),
        ]}],
    },
    "faq": {
        "name": "FAQ dan bantuan",
        "category": "Bisnis",
        "desc": "Pertanyaan yang sering diajukan dalam bentuk kartu, lengkap dengan tombol kontak.",
        "title": "Pusat Bantuan",
        "theme": theme_of("#059669", "#ffffff", "#064e3b", width=680),
        "pages": [{"name": "Bantuan", "elements": [
            H("Pertanyaan yang sering diajukan", 34),
            P("Jawaban cepat untuk hal-hal yang paling sering ditanyakan pelanggan."),
            CARD("Bagaimana cara memesan?", "Pilih produk, isi alamat, lalu bayar. Pesanan diproses di hari yang sama."),
            CARD("Berapa lama pengiriman?", "Biasanya 2 sampai 4 hari kerja, tergantung kota tujuan."),
            CARD("Apakah barang bisa dikembalikan?", "Bisa, maksimal 7 hari setelah barang diterima dan dalam kondisi utuh."),
            CARD("Metode pembayaran apa saja?", "Transfer bank, dompet digital, dan bayar di tempat untuk area tertentu."),
            DIV(),
            H("Masih bingung?", 24),
            B("Hubungi kami", "#"),
            FOOT("Layanan pelanggan: setiap hari 08.00 sampai 20.00"),
        ]}],
    },
    "kontak": {
        "name": "Halaman kontak",
        "category": "Bisnis",
        "desc": "Formulir pesan sederhana dan informasi kontak.",
        "title": "Hubungi Kami",
        "theme": theme_of("#2563eb", "#ffffff", "#1e293b", width=560),
        "pages": [{"name": "Kontak", "elements": [
            H("Hubungi kami", 36),
            P("Tulis pesanmu dan tim kami akan membalas dalam 1 x 24 jam."),
            INP("Nama lengkap", "Nama kamu"),
            INP("Email", "nama@email.com", "email"),
            INP("Pesan", "Apa yang ingin kamu tanyakan?"),
            B("Kirim pesan"),
            DIV(),
            H("Informasi lain", 22),
            LST(["Alamat: Jl. Contoh No. 10", "Telepon: 0812-0000-0000", "Email: halo@contoh.id"]),
            FOOT("© 2026 Contoh Usaha"),
        ]}],
    },
    "promo_app": {
        "name": "Promosi aplikasi mobile",
        "category": "Aplikasi",
        "desc": "Halaman sempit ala ponsel untuk mempromosikan aplikasi dan tombol unduh.",
        "title": "BelanjaKu",
        "theme": theme_of("#db2777", "#fff1f2", "#4c0519", width=480),
        "pages": [{"name": "Beranda", "elements": [
            H("Belanja hemat di genggaman", 34, "center"),
            IMG("shopping", "Aplikasi BelanjaKu", 24, 600, 400),
            P("Ribuan promo harian, gratis ongkir, dan cashback langsung di ponselmu.", "center"),
            LST(["Voucher baru setiap hari", "Lacak pesanan secara langsung", "Bayar dengan satu ketukan"]),
            B("Unduh di Play Store", "#", "center"),
            B("Unduh di App Store", "#", "center"),
            FOOT("© 2026 BelanjaKu"),
        ]}],
    },
    "login": {
        "name": "Masuk dan daftar",
        "category": "Aplikasi",
        "desc": "Dua halaman: formulir masuk dan formulir pendaftaran.",
        "title": "Akun Saya",
        "theme": theme_of("#4f46e5", "#f9fafb", "#111827", width=420),
        "pages": [
            {"name": "Masuk", "elements": [
                SPC(24),
                H("Selamat datang kembali", 30, "center"),
                P("Masuk untuk melanjutkan.", "center"),
                INP("Email", "nama@email.com", "email"),
                INP("Kata sandi", "Masukkan kata sandi", "password"),
                B("Masuk"),
                P("Belum punya akun? Buka halaman Daftar.", "center"),
            ]},
            {"name": "Daftar", "elements": [
                SPC(24),
                H("Buat akun baru", 30, "center"),
                P("Hanya butuh satu menit.", "center"),
                INP("Nama lengkap", "Nama kamu"),
                INP("Email", "nama@email.com", "email"),
                INP("Kata sandi", "Minimal 8 karakter", "password"),
                B("Daftar"),
            ]},
        ],
    },
    "coming_soon": {
        "name": "Segera hadir",
        "category": "Aplikasi",
        "desc": "Halaman tema gelap untuk mengumpulkan email sebelum peluncuran.",
        "title": "Segera Hadir",
        "theme": theme_of("#0284c7", "#0f172a", "#f8fafc", width=520),
        "pages": [{"name": "Beranda", "elements": [
            SPC(80),
            H("Segera hadir", 52, "center"),
            P("Kami sedang menyiapkan sesuatu yang baru. Tinggalkan emailmu untuk jadi yang pertama tahu.", "center"),
            INP("Email", "nama@email.com", "email"),
            B("Beri tahu saya", "", "center"),
            SPC(40),
            FOOT("Peluncuran: kuartal pertama 2027"),
        ]}],
    },
    "katalog_kopi": {
        "name": "Katalog produk",
        "category": "Toko dan kuliner",
        "desc": "Etalase produk dengan galeri foto, kartu harga, dan tombol pesan.",
        "title": "Kopi Nusantara",
        "theme": theme_of("#ea580c", "#fffbeb", "#292524", width=840),
        "pages": [{"name": "Katalog", "elements": [
            NAV("Kopi Nusantara", [("Katalog", "#"), ("Cara pesan", "#"), ("Kontak", "#")]),
            SPC(8),
            H("Biji kopi pilihan dari berbagai daerah", 36),
            P("Disangrai segar setiap minggu dan dikirim ke seluruh Indonesia."),
            GAL(["coffee1", "coffee2", "coffee3"], 3),
            CARD("Arabika Gayo", "Rp 85.000 per 250 gr. Aroma floral dengan asam yang lembut."),
            CARD("Robusta Lampung", "Rp 60.000 per 250 gr. Pahit tegas dan body tebal."),
            CARD("Toraja Sapan", "Rp 95.000 per 250 gr. Rasa rempah dengan sentuhan cokelat."),
            B("Pesan sekarang", "#", "center"),
            FOOT("Pengiriman setiap Senin dan Kamis"),
        ]}],
    },
    "menu_restoran": {
        "name": "Menu restoran",
        "category": "Toko dan kuliner",
        "desc": "Halaman warung atau restoran: menu favorit, jam buka, dan tombol pesan.",
        "title": "Warung Bu Sari",
        "theme": theme_of("#b45309", "#fff7ed", "#431407", "Serif klasik", 720),
        "pages": [{"name": "Menu", "elements": [
            NAV("Warung Bu Sari", [("Menu", "#"), ("Lokasi", "#"), ("Pesan", "#")]),
            SPC(8),
            H("Masakan rumahan, rasa juara", 40, "center"),
            IMG("food", "Hidangan warung", 12),
            H("Menu favorit", 28),
            LST([
                "Nasi gudeg komplit: Rp 28.000",
                "Ayam bakar madu: Rp 32.000",
                "Soto betawi: Rp 30.000",
                "Es teh manis: Rp 6.000",
            ]),
            DIV(),
            H("Jam buka", 24),
            P("Setiap hari, pukul 08.00 sampai 21.00."),
            B("Pesan sekarang", "#", "center"),
            FOOT("Terima pesanan katering minimal 20 porsi"),
        ]}],
    },
    "harga_umkm": {
        "name": "Daftar harga UMKM",
        "category": "Toko dan kuliner",
        "desc": "Daftar harga dan cara pesan untuk usaha rumahan.",
        "title": "Kue Basah Bu Lina",
        "theme": theme_of("#16a34a", "#f0fdf4", "#14532d", width=640),
        "pages": [{"name": "Harga", "elements": [
            H("Kue basah Bu Lina", 36, "center"),
            P("Dibuat segar setiap pagi tanpa pengawet. Pesan H-1 ya.", "center"),
            IMG("cake", "Aneka kue basah", 16),
            H("Daftar harga", 26),
            LST([
                "Risoles isi ragout: Rp 3.500 per buah",
                "Lemper ayam: Rp 3.000 per buah",
                "Kue lapis: Rp 2.500 per potong",
                "Paket arisan (30 pcs): Rp 90.000",
            ]),
            H("Cara pesan", 26),
            LST(["Pilih kue dan jumlahnya", "Kirim pesanan lewat WhatsApp", "Bayar saat kue diantar"], "number"),
            B("Pesan lewat WhatsApp", "#", "center"),
            FOOT("Antar gratis area dalam kota"),
        ]}],
    },
    "portofolio": {
        "name": "Portofolio pribadi",
        "category": "Pribadi",
        "desc": "Tiga halaman: perkenalan, proyek dengan galeri, dan formulir kontak.",
        "title": "Rani Maharani",
        "theme": theme_of("#0f766e", "#fafaf9", "#1c1917", "Serif klasik", 720),
        "pages": [
            {"name": "Beranda", "elements": [
                SPC(16),
                H("Halo, saya Rani", 44),
                P("Desainer grafis dan ilustrator. Saya membantu merek kecil tampil rapi dan mudah diingat."),
                IMG("portrait", "Foto Rani", 16),
                B("Lihat proyek", "#"),
            ]},
            {"name": "Proyek", "elements": [
                H("Proyek pilihan", 34),
                GAL(["design1", "design2", "design3", "design4"], 2, 10),
                H("Layanan", 24),
                LST(["Desain logo dan identitas merek", "Ilustrasi untuk buku dan kemasan", "Desain media sosial"]),
            ]},
            {"name": "Kontak", "elements": [
                H("Mari berkolaborasi", 34),
                P("Ceritakan kebutuhanmu dan saya balas dalam dua hari kerja."),
                INP("Nama", "Nama kamu"),
                INP("Email", "nama@email.com", "email"),
                INP("Pesan", "Ceritakan proyekmu"),
                B("Kirim pesan"),
                FOOT("© 2026 Rani Maharani"),
            ]},
        ],
    },
    "cv_online": {
        "name": "CV online",
        "category": "Pribadi",
        "desc": "Riwayat kerja, pendidikan, dan keahlian dalam satu halaman rapi.",
        "title": "Budi Santoso",
        "theme": theme_of("#334155", "#ffffff", "#0f172a", "Serif klasik", 700),
        "pages": [{"name": "CV", "elements": [
            H("Budi Santoso", 40),
            P("Analis data. budi@contoh.id"),
            DIV(),
            H("Pengalaman", 26),
            LST([
                "Analis Data, PT Maju Bersama (2023 sampai sekarang)",
                "Staf Riset, Lembaga Survei Nusantara (2021 sampai 2023)",
            ]),
            H("Pendidikan", 26),
            LST(["S1 Statistika, Universitas Contoh (2017 sampai 2021)"]),
            H("Keahlian", 26),
            LST(["SQL dan Python", "Visualisasi data", "Penulisan laporan"]),
            B("Unduh CV", "#"),
        ]}],
    },
    "link_bio": {
        "name": "Link in bio",
        "category": "Pribadi",
        "desc": "Halaman sempit berisi foto profil dan deretan tombol tautan.",
        "title": "Nadia Creates",
        "theme": theme_of("#7c3aed", "#faf5ff", "#2e1065", width=420),
        "pages": [{"name": "Tautan", "elements": [
            SPC(16),
            IMG("avatar", "Foto profil", 48, 400, 400),
            H("@nadia.creates", 28, "center"),
            P("Kreator konten fotografi dan perjalanan.", "center"),
            B("Instagram", "#", "center"),
            B("YouTube", "#", "center"),
            B("Toko preset foto", "#", "center"),
            B("Kerja sama", "#", "center"),
            FOOT("Terima kasih sudah mampir"),
        ]}],
    },
    "blog": {
        "name": "Artikel blog",
        "category": "Konten",
        "desc": "Tata letak artikel dengan gambar sampul, poin penting, dan rekomendasi bacaan.",
        "title": "Catatan Dimas",
        "theme": theme_of("#1d4ed8", "#ffffff", "#1f2937", "Serif klasik", 680),
        "pages": [{"name": "Artikel", "elements": [
            H("Belajar menulis setiap hari", 38),
            P("Oleh Dimas, 5 menit baca"),
            IMG("writing", "Meja menulis", 8),
            P("Menulis bukan soal bakat. Ia kebiasaan kecil yang diulang sampai terasa ringan. Mulailah dari satu paragraf sehari."),
            H("Poin penting", 26),
            LST(["Tetapkan waktu menulis yang sama", "Tulis dulu, rapikan belakangan", "Baca ulang dengan suara keras"], "number"),
            DIV(),
            CARD("Baca juga", "Tiga kebiasaan kecil yang membuat tulisanmu lebih tajam."),
            FOOT("© 2026 Catatan Dimas"),
        ]}],
    },
    "kursus": {
        "name": "Kursus online",
        "category": "Pendidikan",
        "desc": "Halaman pendaftaran kelas: materi, pilihan paket, dan tombol daftar.",
        "title": "Kelas Kode",
        "theme": theme_of("#0369a1", "#f0f9ff", "#0c4a6e", width=760),
        "pages": [{"name": "Kelas", "elements": [
            NAV("Kelas Kode", [("Materi", "#"), ("Paket", "#"), ("Masuk", "#")]),
            SPC(8),
            H("Belajar pemrograman dari nol", 40),
            P("Kelas daring dengan latihan langsung dan mentor yang menjawab pertanyaanmu."),
            B("Daftar kelas", "#"),
            IMG("coding", "Belajar pemrograman", 12),
            H("Yang akan kamu pelajari", 28),
            LST(["Dasar logika pemrograman", "Membuat halaman web", "Mengolah data sederhana", "Membuat aplikasi kecil", "Proyek akhir"], "number"),
            H("Pilih paket", 28),
            CARD("Reguler", "Rp 299.000. Akses materi selama 3 bulan."),
            CARD("Intensif", "Rp 599.000. Akses 1 tahun dan sesi mentoring mingguan."),
            FOOT("Garansi uang kembali 7 hari"),
        ]}],
    },
    "undangan": {
        "name": "Undangan acara",
        "category": "Acara",
        "desc": "Undangan digital dengan waktu, tempat, dan konfirmasi kehadiran.",
        "title": "Ayu dan Bagas",
        "theme": theme_of("#be185d", "#fdf2f8", "#500724", "Serif klasik", 600),
        "pages": [{"name": "Undangan", "elements": [
            SPC(16),
            H("Ayu dan Bagas", 44, "center"),
            P("Dengan hormat mengundang Anda untuk hadir di hari bahagia kami.", "center"),
            IMG("wedding", "Foto pasangan", 24, 600, 400),
            H("Waktu dan tempat", 26, "center"),
            P("Sabtu, 12 Desember 2026, pukul 10.00 WIB", "center"),
            P("Gedung Serbaguna Melati, Jl. Merdeka No. 12", "center"),
            B("Lihat lokasi", "#", "center"),
            DIV(),
            H("Konfirmasi kehadiran", 24, "center"),
            INP("Nama", "Nama Anda"),
            INP("Jumlah tamu", "1", "number"),
            B("Konfirmasi", "", "center"),
            FOOT("Merupakan kehormatan bagi kami atas kehadiran Anda"),
        ]}],
    },
    "konferensi": {
        "name": "Jadwal acara dan pembicara",
        "category": "Acara",
        "desc": "Halaman meetup atau seminar: jadwal, foto pembicara, dan tombol tiket.",
        "title": "Dev Meetup 2026",
        "theme": theme_of("#4338ca", "#eef2ff", "#1e1b4b", width=720),
        "pages": [{"name": "Acara", "elements": [
            H("Dev Meetup 2026", 38, "center"),
            P("Sabtu, 14 November 2026, di Aula Utama. Gratis untuk 200 peserta pertama.", "center"),
            B("Daftar tiket", "#", "center"),
            H("Jadwal", 26),
            LST([
                "09.00 Registrasi",
                "09.30 Pembukaan",
                "10.00 Sesi 1: Membangun aplikasi cepat",
                "13.00 Sesi 2: Data untuk pemula",
                "15.30 Diskusi panel",
            ]),
            H("Pembicara", 26),
            GAL(["speaker1", "speaker2", "speaker3", "speaker4"], 4, 48),
            FOOT("Ditemani kopi dan makan siang"),
        ]}],
    },
    "dashboard": {
        "name": "Ringkasan statistik",
        "category": "Data",
        "desc": "Kartu angka penting, daftar tugas, dan kolom pencarian laporan.",
        "title": "Ringkasan Mingguan",
        "theme": theme_of("#0891b2", "#f8fafc", "#0f172a", width=900),
        "pages": [{"name": "Ringkasan", "elements": [
            H("Ringkasan minggu ini", 34),
            CARD("Pengunjung", "12.480, naik 8% dari minggu lalu."),
            CARD("Pesanan", "342, naik 3% dari minggu lalu."),
            CARD("Pendapatan", "Rp 48,2 juta."),
            DIV(),
            H("Tugas hari ini", 24),
            LST(["Balas ulasan pelanggan", "Perbarui stok produk", "Kirim laporan ke tim"]),
            INP("Cari laporan", "Ketik kata kunci"),
            B("Unduh laporan"),
        ]}],
    },
    # ------------------------------------------------------------------
    # Template tambahan (memakai komponen bar)
    # ------------------------------------------------------------------
    "profil_perusahaan": {
        "name": "Profil perusahaan",
        "category": "Bisnis",
        "desc": "Pengumuman, angka pencapaian, daftar layanan, dan tautan sosial.",
        "title": "Karya Mandiri Teknik",
        "theme": theme_of("#1d4ed8", "#f8fafc", "#0f172a", width=820),
        "pages": [{"name": "Profil", "elements": [
            BAR("announcement", text="Kantor cabang baru kami kini buka di Surabaya.", link_text="Selengkapnya", link="#"),
            NAV("Karya Mandiri", [("Tentang", "#"), ("Layanan", "#"), ("Kontak", "#")]),
            SPC(8),
            H("Mitra teknik tepercaya sejak 2009", 38),
            P("Kami membantu pabrik dan gudang menjaga mesin tetap berjalan, dengan teknisi bersertifikat dan jadwal perawatan yang jelas."),
            IMG("factory", "Tim teknisi di lapangan"),
            BAR("statsbar", items="15 tahun|Pengalaman\n480|Klien aktif\n98%|Tepat waktu"),
            H("Layanan kami", 28),
            CARD("Perawatan berkala", "Pemeriksaan terjadwal supaya mesin tidak berhenti mendadak."),
            CARD("Perbaikan darurat", "Teknisi tiba dalam empat jam untuk area Jawa Timur."),
            CARD("Audit efisiensi", "Laporan tertulis berisi temuan dan saran penghematan energi."),
            BAR("socialbar", items="LinkedIn|#|work\nEmail|#|mail\nTelepon|#|call"),
            FOOT("© 2026 PT Karya Mandiri Teknik"),
        ]}],
    },
    "layanan_jasa": {
        "name": "Layanan jasa rumah",
        "category": "Bisnis",
        "desc": "Kategori layanan dengan ikon, alur kerja bertahap, dan ajakan memesan.",
        "title": "Sigap Rumah",
        "theme": theme_of("#0d9488", "#ffffff", "#134e4a", width=700),
        "pages": [{"name": "Layanan", "elements": [
            NAV("Sigap Rumah", [("Layanan", "#"), ("Harga", "#"), ("Bantuan", "#")]),
            SPC(8),
            H("Masalah rumah beres tanpa repot", 36),
            P("Pilih jenis layanan, tentukan jadwal, dan teknisi kami datang ke rumahmu."),
            BAR("categorybar", items="Servis AC|ac_unit\nListrik|bolt\nPipa|plumbing\nCat|format_paint\nKebersihan|cleaning_services"),
            H("Cara kerja", 26),
            BAR("stepper", steps="Pesan\nTeknisi datang\nPengerjaan\nSelesai", current=2),
            CARD("Garansi 30 hari", "Bila masalah muncul lagi, kami perbaiki tanpa biaya tambahan."),
            CARD("Harga dimuka", "Biaya diberitahukan sebelum pengerjaan dimulai."),
            B("Pesan teknisi", "#", "center"),
            FOOT("Layanan setiap hari, pukul 07.00 sampai 21.00"),
        ]}],
    },
    "tim_kami": {
        "name": "Tim kami",
        "category": "Bisnis",
        "desc": "Perkenalan anggota tim dengan bar profil dan ajakan bergabung.",
        "title": "Studio Lentera",
        "theme": theme_of("#7c3aed", "#faf5ff", "#2e1065", width=640),
        "pages": [{"name": "Tim", "elements": [
            NAV("Studio Lentera", [("Karya", "#"), ("Tim", "#"), ("Kontak", "#")]),
            SPC(8),
            H("Orang-orang di balik Lentera", 34),
            P("Tim kecil dengan latar desain, riset, dan teknologi yang bekerja dari tiga kota."),
            BAR("profilebar", name="Dewi Anggraini", role="Direktur kreatif", action="Profil"),
            BAR("profilebar", name="Bagas Pratama", role="Insinyur utama", action="Profil"),
            BAR("profilebar", name="Citra Lestari", role="Peneliti pengguna", action="Profil"),
            BAR("profilebar", name="Fajar Nugroho", role="Manajer proyek", action="Profil"),
            DIV(),
            H("Ingin bergabung?", 26, "center"),
            B("Lihat lowongan", "#", "center"),
            FOOT("© 2026 Studio Lentera"),
        ]}],
    },
    "dashboard_admin": {
        "name": "Dasbor admin",
        "category": "Data",
        "desc": "Menu samping, angka ringkas, bar progres, peringatan, toolbar, dan paginasi.",
        "title": "Toko Kita Admin",
        "theme": theme_of("#4f46e5", "#f8fafc", "#0f172a", width=920),
        "pages": [{"name": "Dasbor", "elements": [
            BAR("sidemenu", title="Toko Kita", active=1,
                items="Dasbor|dashboard\nPesanan|shopping_bag\nPelanggan|group\nLaporan|bar_chart\nPengaturan|settings"),
            H("Dasbor hari ini", 30),
            BAR("statsbar", items="128|Pesanan\nRp 9,4 jt|Pendapatan\n32|Pelanggan baru\n4,7|Rating"),
            BAR("statusbar", kind="warning", title="Stok menipis", text="Lima produk tersisa kurang dari sepuluh unit."),
            H("Penggunaan sumber daya", 22),
            BAR("progressbar", label="Penyimpanan foto produk", value=72),
            BAR("progressbar", label="Kuota pesan WhatsApp", value=45),
            BAR("progressbar", label="Kuota iklan bulan ini", value=88),
            BAR("toolbar", items="Tambah produk|add\nUnduh laporan|download\nFilter|filter_list\nMuat ulang|refresh"),
            LST(["Konfirmasi 6 pembayaran", "Balas 3 pertanyaan pelanggan", "Cetak 12 label pengiriman"]),
            BAR("pagination", pages=8, current=2),
        ]}],
    },
    "pengaturan": {
        "name": "Halaman pengaturan",
        "category": "Aplikasi",
        "desc": "Breadcrumb, tab pengaturan, isian akun, dan tombol simpan.",
        "title": "Pengaturan Akun",
        "theme": theme_of("#2563eb", "#ffffff", "#111827", width=620),
        "pages": [{"name": "Akun", "elements": [
            BAR("breadcrumb", items="Beranda\nAkun\nPengaturan"),
            H("Pengaturan", 32),
            BAR("tabbar", items="Akun\nNotifikasi\nPrivasi", active=1),
            INP("Nama lengkap", "Nama sesuai KTP"),
            INP("Email", "nama@contoh.com", "email"),
            INP("Nomor telepon", "08xxxxxxxxxx", "tel"),
            INP("Kata sandi baru", "Minimal 8 karakter", "password"),
            BAR("statusbar", kind="info", title="Tips", text="Gunakan kata sandi yang berbeda dari akun lain."),
            B("Simpan perubahan", "", "left"),
        ]}],
    },
    "onboarding": {
        "name": "Onboarding aplikasi",
        "category": "Aplikasi",
        "desc": "Tiga layar pengenalan dengan bar langkah di setiap halaman.",
        "title": "Catatin",
        "theme": theme_of("#f97316", "#fffaf5", "#431407", "Sans-serif modern", 420),
        "pages": [
            {"name": "Mulai", "elements": [
                BAR("stepper", steps="Mulai\nProfil\nSelesai", current=1),
                IMG("onboard1", "Ilustrasi catatan", 20, 600, 420),
                H("Catat apa saja, di mana saja", 30, "center"),
                P("Simpan ide, daftar belanja, dan tugas dalam satu tempat yang rapi.", "center"),
                B("Lanjut", "#", "center"),
            ]},
            {"name": "Profil", "elements": [
                BAR("stepper", steps="Mulai\nProfil\nSelesai", current=2),
                H("Kenalan dulu", 30, "center"),
                INP("Nama panggilan", "Mau dipanggil apa?"),
                INP("Email", "nama@contoh.com", "email"),
                B("Lanjut", "#", "center"),
            ]},
            {"name": "Selesai", "elements": [
                BAR("stepper", steps="Mulai\nProfil\nSelesai", current=3),
                IMG("onboard3", "Ilustrasi selesai", 20, 600, 420),
                H("Semua siap", 30, "center"),
                P("Buat catatan pertamamu sekarang.", "center"),
                B("Mulai mencatat", "#", "center"),
            ]},
        ],
    },
    "detail_produk": {
        "name": "Detail produk",
        "category": "Toko dan kuliner",
        "desc": "Foto produk, rating bintang, spesifikasi, dan bar harga yang menempel di bawah.",
        "title": "Tas Anyaman Lombok",
        "theme": theme_of("#b45309", "#fffbeb", "#451a03", "Serif klasik", 640),
        "pages": [{"name": "Produk", "elements": [
            BAR("breadcrumb", items="Beranda\nTas\nTas Anyaman Lombok"),
            IMG("bag", "Tas anyaman", 16, 800, 560),
            H("Tas Anyaman Lombok", 32),
            BAR("ratingbar", label="Ulasan pembeli", value=4.5, count="(212 ulasan)"),
            P("Dianyam tangan oleh pengrajin Lombok dari serat pandan, ringan dan kuat untuk dipakai sehari-hari."),
            LST(["Bahan: pandan dan kulit sintetis", "Ukuran: 32 x 24 x 12 cm", "Berat: 480 gram", "Warna: cokelat alami"]),
            CARD("Garansi pengrajin", "Jahitan lepas dalam 60 hari kami perbaiki gratis."),
            BAR("pricebar", price="Rp 189.000", caption="Gratis ongkir Jawa dan Bali", button="Beli sekarang", link="#"),
        ]}],
    },
    "checkout": {
        "name": "Keranjang dan checkout",
        "category": "Toko dan kuliner",
        "desc": "Langkah pembayaran, isian alamat, kode promo, dan ringkasan harga.",
        "title": "Checkout",
        "theme": theme_of("#16a34a", "#ffffff", "#14532d", width=620),
        "pages": [{"name": "Alamat", "elements": [
            BAR("breadcrumb", items="Keranjang\nCheckout"),
            BAR("stepper", steps="Keranjang\nAlamat\nPembayaran\nSelesai", current=2),
            H("Alamat pengiriman", 28),
            INP("Nama penerima", "Nama lengkap"),
            INP("Alamat", "Jalan, nomor, kecamatan"),
            INP("Nomor telepon", "08xxxxxxxxxx", "tel"),
            BAR("statusbar", kind="success", title="Promo terpasang", text="Potongan Rp 15.000 untuk pesanan pertama."),
            CARD("Ringkasan pesanan", "2 barang, ongkir Rp 12.000, potongan Rp 15.000."),
            BAR("pricebar", price="Rp 246.000", caption="Total yang dibayar", button="Lanjut bayar", link="#"),
        ]}],
    },
    "galeri_foto": {
        "name": "Galeri foto",
        "category": "Konten",
        "desc": "Pencarian, filter kategori, dua galeri, paginasi, dan tombol unggah melayang.",
        "title": "Galeri Nusantara",
        "theme": theme_of("#e11d48", "#fff1f2", "#4c0519", width=860),
        "pages": [{"name": "Galeri", "elements": [
            H("Galeri Nusantara", 34),
            BAR("searchbar", placeholder="Cari foto atau fotografer", button="Cari"),
            BAR("filterbar", items="Semua\nAlam\nKota\nPotret\nKuliner", active=1),
            GAL(["g1", "g2", "g3", "g4", "g5", "g6"], 3, 12),
            GAL(["g7", "g8", "g9"], 3, 12),
            BAR("pagination", pages=12, current=1),
            BAR("fab", icon="add_a_photo", text="Unggah", align="right"),
        ]}],
    },
    "testimoni": {
        "name": "Testimoni dan ulasan",
        "category": "Konten",
        "desc": "Rating rata-rata, statistik kepuasan, dan kutipan pelanggan.",
        "title": "Kata Mereka",
        "theme": theme_of("#d97706", "#ffffff", "#1f2937", width=680),
        "pages": [{"name": "Ulasan", "elements": [
            H("Kata pelanggan kami", 34, "center"),
            BAR("ratingbar", label="Rata-rata dari semua ulasan", value=4.8, count="(1.204 ulasan)"),
            BAR("statsbar", items="96%|Merekomendasikan\n4,8|Rating\n1,2 rb|Ulasan"),
            CARD("Rina, Bandung", "Pesanan sampai lebih cepat dari perkiraan dan kemasannya rapi."),
            CARD("Yoga, Medan", "Adminnya sabar menjawab semua pertanyaan sebelum saya membeli."),
            CARD("Mega, Makassar", "Sudah tiga kali pesan ulang, kualitasnya konsisten."),
            B("Tulis ulasanmu", "#", "center"),
            FOOT("Ulasan diverifikasi dari pembelian nyata"),
        ]}],
    },
    "pricing": {
        "name": "Paket harga",
        "category": "Bisnis",
        "desc": "Tiga paket langganan, pilihan periode, dan pengumuman diskon tahunan.",
        "title": "Paket Harga",
        "theme": theme_of("#0ea5e9", "#f0f9ff", "#0c4a6e", width=700),
        "pages": [{"name": "Harga", "elements": [
            BAR("announcement", text="Hemat 20% dengan paket tahunan.", link_text="Pilih tahunan", link="#"),
            H("Pilih paket yang pas", 36, "center"),
            P("Mulai gratis, naik paket kapan saja tanpa kehilangan data.", "center"),
            BAR("filterbar", items="Bulanan\nTahunan", active=1),
            CARD("Starter, Rp 0", "Satu proyek, 100 MB penyimpanan, dukungan komunitas."),
            CARD("Pro, Rp 99.000 per bulan", "Proyek tanpa batas, 20 GB penyimpanan, dukungan email."),
            CARD("Bisnis, Rp 299.000 per bulan", "Lima anggota tim, 200 GB penyimpanan, dukungan prioritas."),
            LST(["Semua paket memakai enkripsi data", "Batalkan kapan saja", "Faktur pajak tersedia"]),
            B("Mulai gratis", "#", "center"),
        ]}],
    },
    "halaman_404": {
        "name": "Halaman 404",
        "category": "Utilitas",
        "desc": "Pesan halaman tidak ditemukan dengan pencarian dan tombol kembali.",
        "title": "Tidak ditemukan",
        "theme": theme_of("#6366f1", "#ffffff", "#1e1b4b", width=560),
        "pages": [{"name": "404", "elements": [
            BAR("breadcrumb", items="Beranda\nTidak ditemukan"),
            SPC(40),
            H("404", 72, "center"),
            H("Halaman tidak ditemukan", 26, "center"),
            P("Alamat yang kamu buka mungkin salah ketik atau halamannya sudah dipindahkan. Coba cari dari sini.", "center"),
            BAR("searchbar", placeholder="Cari halaman", button="Cari"),
            B("Kembali ke beranda", "#", "center"),
        ]}],
    },
    "newsletter": {
        "name": "Langganan newsletter",
        "category": "Konten",
        "desc": "Formulir email, tautan sosial, dan bar persetujuan cookie.",
        "title": "Surat Senin",
        "theme": theme_of("#be185d", "#fdf2f8", "#500724", "Serif klasik", 560),
        "pages": [{"name": "Langganan", "elements": [
            BAR("announcement", text="Edisi terbaru terbit setiap Senin pagi.", link_text="Baca arsip", link="#"),
            SPC(16),
            H("Satu surel seminggu, isinya padat", 36, "center"),
            P("Ringkasan kabar teknologi dan desain yang bisa dibaca dalam lima menit.", "center"),
            INP("Alamat email", "nama@contoh.com", "email"),
            B("Berlangganan", "#", "center"),
            BAR("socialbar", items="Instagram|#|photo_camera\nThreads|#|forum\nRSS|#|rss_feed"),
            BAR("cookiebar", text="Kami memakai cookie untuk mengukur jumlah pembaca.", accept="Terima", decline="Tolak"),
            FOOT("Berhenti berlangganan kapan saja"),
        ]}],
    },
    "donasi": {
        "name": "Penggalangan donasi",
        "category": "Sosial",
        "desc": "Progres dana terkumpul, pilihan nominal, dan bar harga untuk donasi.",
        "title": "Perpustakaan Desa",
        "theme": theme_of("#dc2626", "#fff7ed", "#450a0a", width=640),
        "pages": [{"name": "Donasi", "elements": [
            IMG("library", "Anak-anak membaca buku", 16, 800, 440),
            H("Bantu bangun perpustakaan desa", 32),
            P("Dana dipakai untuk rak buku, 1.000 judul buku anak, dan honor pustakawan selama setahun."),
            BAR("progressbar", label="Terkumpul Rp 38 juta dari Rp 50 juta", value=76),
            BAR("statsbar", items="412|Donatur\n12|Hari tersisa\n76%|Tercapai"),
            H("Pilih nominal", 22),
            BAR("filterbar", items="Rp 25.000\nRp 50.000\nRp 100.000\nLainnya", active=2),
            INP("Nama (boleh disamarkan)", "Hamba Allah"),
            BAR("pricebar", price="Rp 50.000", caption="Donasi pilihanmu", button="Donasi sekarang", link="#"),
        ]}],
    },
    "app_navbawah": {
        "name": "Aplikasi mobile dengan navigasi bawah",
        "category": "Aplikasi",
        "desc": "Pencarian, kategori ikon, filter, kartu rekomendasi, dan navigasi bawah.",
        "title": "Jajan Dekat",
        "theme": theme_of("#ea580c", "#ffffff", "#431407", width=420),
        "pages": [{"name": "Beranda", "elements": [
            H("Mau jajan apa hari ini?", 26),
            BAR("searchbar", placeholder="Cari makanan atau warung", button="Cari"),
            BAR("categorybar", items="Nasi|rice_bowl\nMie|ramen_dining\nKopi|local_cafe\nKue|cake\nSemua|apps"),
            BAR("filterbar", items="Terdekat\nTerlaris\nBuka 24 jam", active=1),
            CARD("Warung Bu Tini", "Nasi pecel dan rempeyek, 350 m dari lokasimu."),
            CARD("Kopi Sudut", "Kopi susu gula aren, buka sampai tengah malam."),
            CARD("Mie Ayam Pak Joko", "Porsi besar, antrean cepat saat jam makan siang."),
            BAR("bottomnav", items="Beranda|home\nJelajah|explore\nPesanan|receipt_long\nProfil|person", active=1),
        ]}],
    },
    "galeri_komponen_baru": {
        "name": "Galeri 50 komponen bar baru",
        "category": "Referensi komponen",
        "desc": "Semua komponen tambahan (navigasi, aksi, informasi, data, formulir, media, sosial, toko) dalam tiga halaman.",
        "title": "Galeri Komponen",
        "theme": theme_of("#4f46e5", "#ffffff", "#1f2937", "Sans-serif modern", 760),
        "pages": [
            {"name": "Navigasi & Aksi", "elements": [
                H("Navigasi", 24),
                BAR("menubar", items="Berkas\nUbah\nTampilan\nBantuan", active=1, action="Masuk"),
                BAR("pilltabs", items="Semua\nTerbaru\nPopuler\nDiskon", active=1),
                BAR("railnav", items="Beranda|home\nTelusuri|explore\nNotifikasi|notifications|3\nProfil|account_circle", active=1),
                BAR("backbar", title="Detail produk", back="Kembali", action="Bagikan", icon="share"),
                BAR("anchorlinks", items="Ringkasan|#ringkasan\nFitur|#fitur\nHarga|#harga\nFAQ|#faq", active=1),
                BAR("meganav", title="Jelajahi", items="Analitik|Pantau performa aplikasimu|insights\nOtomasi|Jalankan alur kerja otomatis|bolt\nLaporan|Bagikan hasil ke tim|description"),
                BAR("prevnext", prev="Artikel sebelumnya", prev_note="Dasar Desain", next="Artikel berikutnya", next_note="Panduan Warna"),
                SPC(8),
                H("Aksi", 24),
                BAR("actionbar", primary="Simpan perubahan", secondary="Batal", note="Perubahan tersimpan otomatis"),
                BAR("commandbar", placeholder="Ketik perintah atau cari…", hint="Ctrl K", icon="search"),
                BAR("sortbar", label="Urutkan", options="Terbaru\nTermurah\nTermahal", active=1, view="grid"),
                BAR("sharebar", label="Bagikan ke", items="Salin tautan|link\nWhatsApp|chat\nX|tag\nLainnya|more_horiz"),
                BAR("commentbar", placeholder="Tulis komentar…", button="Kirim", hint="Tekan Enter untuk mengirim"),
                BAR("quickactions", items="Transfer|swap_horiz\nTop up|add_card\nBayar|receipt_long\nRiwayat|history"),
                BAR("linkbar", items="Syarat & ketentuan|#\nKebijakan privasi|#\nBantuan|#\nKarier|#", align="center"),
            ]},
            {"name": "Informasi & Data", "elements": [
                H("Informasi", 24),
                BAR("infobanner", kind="success", title="Pembayaran diterima", text="Pesananmu sedang disiapkan penjual.", link_text="Lihat pesanan", link="#"),
                BAR("tipbar", title="Tips", text="Tekan Ctrl + K untuk membuka daftar perintah cepat.", dismiss="Mengerti"),
                BAR("quotebar", text="Desain yang baik terasa sederhana, bukan sepi.", author="Rani Kusuma", role="Perancang Produk"),
                BAR("countdownbar", label="Promo berakhir dalam", items="02|Jam\n45|Menit\n10|Detik"),
                BAR("stockbar", label="Stok tersisa 8 dari 40", note="Dikirim hari ini juga", status="low", value=20),
                BAR("livebar", title="Kelas daring: Dasar UI", viewers="1.240 menonton", button="Tonton"),
                BAR("totalbar", items="Subtotal|Rp 240.000\nOngkir|Rp 18.000\nDiskon|- Rp 20.000", total_label="Total", total="Rp 238.000"),
                SPC(8),
                H("Data", 24),
                BAR("tablebar", columns="Produk|45\nHarga|25\nStatus|30", row="Kaos Polos|Rp 89.000|Aktif"),
                BAR("comparebar", title="Penjualan", items="Tahun ini|78\nTahun lalu|54", caption="Naik 24% dibanding tahun lalu"),
                BAR("sparkbar", label="Kunjungan 7 hari", values="12, 18, 9, 22, 30, 26, 34", caption="34 hari ini"),
                BAR("legendbar", title="Status", items="Selesai|#22c55e\nBerjalan|#f59e0b\nGagal|#ef4444"),
                BAR("timelinebar", items="Pesanan dibuat|09:12\nDikemas|11:40\nDikirim|16:05", current=3),
                BAR("rangebar", label="Rentang harga", min_label="Rp 0", max_label="Rp 1.000.000", low=20, high=70),
                BAR("calendarstrip", items="Sen|12\nSel|13\nRab|14\nKam|15\nJum|16\nSab|17", active=3),
            ]},
            {"name": "Formulir, Media, Sosial & Toko", "elements": [
                H("Formulir", 24),
                BAR("formbar", label="Nama lengkap", placeholder="Ketik nama…", kind="text", button="Kirim"),
                BAR("newsletterbar", title="Kabar terbaru tiap minggu", placeholder="email@contoh.com", button="Langganan", note="Tanpa spam. Bisa berhenti kapan saja."),
                BAR("otpbar", label="Masukkan kode verifikasi", digits=6, note="Kode dikirim ke nama@email.com"),
                BAR("tagsinputbar", placeholder="Tambah tag…", tags="desain\nantarmuka\nmobile", button="Tambah"),
                BAR("sliderbar", label="Volume", value=60, min_label="0", max_label="100", unit="%"),
                BAR("switchbar", items="Notifikasi email|on\nPromo mingguan|off\nMode gelap|on"),
                BAR("loginbar", title="Masuk ke akunmu", user="nama@email.com", placeholder="Kata sandi", button="Masuk", note="Lupa kata sandi?"),
                SPC(8),
                H("Media", 24),
                BAR("playbar", title="Judul lagu", artist="Nama artis", value=32, current="1:12", duration="3:48", playing="pause"),
                BAR("storiesbar", items="Ceritamu||add\nRani|https://i.pravatar.cc/96?img=5\nBudi|https://i.pravatar.cc/96?img=12\nSari|https://i.pravatar.cc/96?img=32"),
                BAR("thumbstripbar", items="https://picsum.photos/seed/mini1/200/140\nhttps://picsum.photos/seed/mini2/200/140\nhttps://picsum.photos/seed/mini3/200/140", active=1),
                BAR("captionsbar", text="Selamat datang di episode kali ini.", lang="Bahasa Indonesia", button="CC"),
                BAR("recordbar", label="Merekam…", time="00:24", button="Kirim", wave="4,9,14,7,17,11,6,13,8,16,5,10"),
                SPC(8),
                H("Sosial & Toko", 24),
                BAR("reactionbar", items="Suka|thumb_up|128\nCinta|favorite|32\nKomentar|chat_bubble|14"),
                BAR("userstackbar", items="Rani|https://i.pravatar.cc/64?img=9\nBudi|https://i.pravatar.cc/64?img=14\nSari|\nDewi|", count="+12", note="bergabung di kelas ini"),
                BAR("reviewbar", name="Budi Santoso", rating=4.5, time="2 hari lalu", text="Pengiriman cepat, kualitas sesuai deskripsi."),
                BAR("chatbar", name="Rani Kusuma", avatar="https://i.pravatar.cc/64?img=20", message="Paketnya sudah sampai, terima kasih!", time="09:24", unread="3"),
                BAR("followbar", name="Rani Kusuma", handle="@ranikusuma · 12,4 rb pengikut", button="Ikuti", note="Mengikuti akunmu"),
                BAR("productbar", image="https://picsum.photos/seed/produk7/160/160", name="Kaos Katun Polos", note="Ukuran M · Putih", price="Rp 89.000", old_price="Rp 129.000", button="Tambah"),
                BAR("couponbar", code="HEMAT20", note="Diskon 20% maks. Rp 50.000", expires="Berlaku sampai 31 Des", button="Pakai"),
                BAR("shippingbar", label="Belanja Rp 75.000 lagi untuk gratis ongkir", value=62, min_label="Rp 0", max_label="Gratis ongkir"),
                BAR("paymentbar", items="Kartu kredit|•••• 4242|credit_card\nTransfer bank|BCA|account_balance\nDompet digital|Saldo Rp 25.000|wallet", active=1, note="Pilih satu metode pembayaran"),
                BAR("cartbar", count=3, label="Keranjang belanja", total="Rp 267.000", button="Checkout"),
            ]},
        ],
    },
    "galeri_arsitektur": {
        "name": "Galeri arsitektur",
        "category": "Galeri",
        "desc": "Etalase proyek arsitektur: header aplikasi, filter, dua galeri, dan paginasi.",
        "title": "Ruang Beton",
        "theme": theme_of("#b45309", "#f8fafc", "#1f2937", "Sans-serif modern", 880),
        "pages": [{"name": "Proyek", "elements": [
            BAR("appbar", title="Ruang Beton", subtitle="38 proyek terkurasi", back="Kembali",
                action="Hubungi", icon="mail"),
            H("Arsitektur yang tumbuh dari tempatnya", 32),
            P("Kumpulan proyek rumah tinggal, kafe, dan ruang publik dari 12 kota."),
            BAR("filterbar", items="Semua\nRumah\nKafe\nPublik\nInterior", active=1),
            GAL(["ars1", "ars2", "ars3", "ars4", "ars5", "ars6"], 3, 14),
            BAR("legendbar", title="Palet material",
                items="Beton ekspos|#9ca3af\nKayu jati|#b45309\nBaja hitam|#374151"),
            GAL(["ars7", "ars8", "ars9"], 3, 14),
            BAR("pagination", pages=8, current=1),
            FOOT("© 2026 Ruang Beton Studio"),
        ]}],
    },
    "galeri_produk": {
        "name": "Galeri produk toko",
        "category": "Galeri",
        "desc": "Etalase katalog dengan pencarian, urutan, kartu produk, dan keranjang.",
        "title": "Toko Rimba",
        "theme": theme_of("#0f766e", "#ffffff", "#0f172a", "Sans-serif modern", 820),
        "pages": [{"name": "Katalog", "elements": [
            NAV("Toko Rimba", [("Baru", "#"), ("Galeri", "#"), ("Kontak", "#")]),
            H("Galeri produk terbaru", 30),
            BAR("searchbar", placeholder="Cari produk atau bahan", button="Cari"),
            BAR("filterbar", items="Semua\nKaos\nTas\nSepatu\nAksesori", active=1),
            GAL(["tok1", "tok2", "tok3", "tok4", "tok5", "tok6"], 3, 10),
            BAR("sortbar", label="Urutkan", options="Terbaru\nTermurah\nTerlaris", active=1, view="grid"),
            BAR("productbar", image=pic("tok7", 160, 160), name="Tas Kanvas Lipat",
                note="Warna tanah · Ukuran M", price="Rp 249.000", old_price="Rp 319.000", button="Tambah"),
            BAR("cartbar", count=2, label="Keranjang belanja", total="Rp 518.000", button="Checkout"),
            BAR("pagination", pages=6, current=2),
            FOOT("Gratis ongkir untuk pembelian di atas Rp 300.000"),
        ]}],
    },
    "galeri_seni": {
        "name": "Galeri karya seni",
        "category": "Galeri",
        "desc": "Pameran daring dengan kutipan kurator, dua kelompok karya, dan tautan katalog.",
        "title": "Pameran Rupa",
        "theme": theme_of("#7c3aed", "#faf5ff", "#2e1065", "Serif elegan", 760),
        "pages": [{"name": "Pameran", "elements": [
            BAR("appbar", title="Pameran Rupa", subtitle="15 karya · 4 seniman", back="Beranda",
                action="Bagikan", icon="share"),
            H("Warna di antara ingatan", 34),
            P("Lukisan akrilik dan karya kertas dari sanggar di Yogyakarta, dipamerkan secara daring."),
            GAL(["seni1", "seni2", "seni3", "seni4"], 2, 18),
            BAR("quotebar", text="Lukisan adalah cara saya menyimpan yang tidak sempat saya ucapkan.",
                author="Maya Anjani", role="Perupa"),
            DIV(),
            H("Karya pilihan", 24),
            GAL(["seni5", "seni6", "seni7"], 3, 18),
            BAR("linkbar", items="Katalog lengkap|#\nJadwal tur|#\nHubungi kurator|#", align="center"),
            FOOT("Pameran berlangsung sampai 30 November 2026"),
        ]}],
    },
    "galeri_pernikahan": {
        "name": "Galeri pernikahan",
        "category": "Galeri",
        "desc": "Halaman undangan dengan foto utama, hitung mundur, dan galeri momen.",
        "title": "Rani & Budi",
        "theme": theme_of("#be185d", "#fff7f9", "#500724", "Serif klasik", 780),
        "pages": [{"name": "Undangan", "elements": [
            IMG("wedding-hero", "Pasangan pengantin", 18, 900, 460),
            H("Rani & Budi", 34, "center"),
            P("Sabtu, 14 Maret 2026 · Bogor", "center"),
            BAR("countdownbar", label="Menuju hari bahagia", items="128|Hari\n06|Jam\n24|Menit"),
            BAR("subnav", items="Cerita\nGaleri\nLokasi\nHadiah", active=2),
            GAL(["wed1", "wed2", "wed3", "wed4", "wed5", "wed6"], 3, 16),
            P("Terima kasih sudah menjadi bagian dari perjalanan kami.", "center"),
            BAR("sharebar", label="Bagikan ke",
                items="Salin tautan|link\nWhatsApp|chat\nInstagram|photo_camera"),
            FOOT("Undangan digital dibuat dengan UI Builder"),
        ]}],
    },
    "galeri_kuliner": {
        "name": "Galeri kuliner",
        "category": "Galeri",
        "desc": "Galeri hidangan lengkap dengan penilaian tamu, ulasan, dan aksi cepat.",
        "title": "Meja Panas",
        "theme": theme_of("#ea580c", "#fffbf5", "#431407", "Humanis", 780),
        "pages": [{"name": "Hidangan", "elements": [
            H("Meja Panas", 34),
            P("Galeri hidangan baru setiap pekan, dimasak di dapur rumah sejak 2014."),
            BAR("subnav", items="Menu\nGaleri\nCerita dapur", active=2),
            GAL(["kulin1", "kulin2", "kulin3", "kulin4", "kulin5", "kulin6"], 3, 12),
            BAR("ratingbar", label="Penilaian tamu", value=4.7, count="(312 ulasan)"),
            BAR("reviewbar", name="Dewi Larasati", avatar="", rating=5.0, time="3 hari lalu",
                text="Rendangnya pekat dan pedasnya pas, porsinya juga cukup."),
            CARD("Reservasi meja", "Buka Selasa sampai Minggu, pukul 11.00 sampai 21.00."),
            BAR("quickactions", items="Pesan antar|delivery_dining\nReservasi|event_seat\nMenu|menu_book\nLokasi|location_on"),
            FOOT("Dapur Meja Panas · Bandung"),
        ]}],
    },
    "galeri_mode": {
        "name": "Galeri lookbook mode",
        "category": "Galeri",
        "desc": "Lookbook musiman dengan strip gambar mini, kartu produk, dan kupon.",
        "title": "Rumah Mode Netral",
        "theme": theme_of("#111827", "#f9fafb", "#111827", "Serif elegan", 700),
        "pages": [{"name": "Lookbook", "elements": [
            H("Lookbook Musim Hujan", 32),
            P("Delapan padu padan dengan palet netral dan bahan yang tahan hujan."),
            GAL(["look1", "look2", "look3", "look4"], 2, 4),
            BAR("thumbstripbar", items=pic("look5", 200, 140) + "\n" + pic("look6", 200, 140) + "\n"
                + pic("look7", 200, 140), active=1),
            BAR("productbar", image=pic("look8", 160, 160), name="Trench Coat Ringan",
                note="Ukuran S sampai XL · Beige", price="Rp 649.000", old_price="Rp 799.000", button="Tambah"),
            BAR("couponbar", code="HUJAN15", note="Diskon 15% untuk koleksi musim hujan",
                expires="Berlaku sampai 31 Okt", button="Pakai"),
            BAR("pricebar", price="Rp 1.240.000", caption="Harga set lengkap tiga potong",
                button="Beli sekarang", link="#"),
            FOOT("© 2026 Rumah Mode Netral"),
        ]}],
    },
    "galeri_wisata": {
        "name": "Galeri wisata",
        "category": "Galeri",
        "desc": "Panduan perjalanan dengan foto tujuan, rekomendasi tempat, dan bar rute.",
        "title": "Jalur Utara",
        "theme": theme_of("#0284c7", "#f0f9ff", "#082f49", "Sans-serif modern", 820),
        "pages": [{"name": "Perjalanan", "elements": [
            IMG("wisata-hero", "Danau di pagi hari", 16, 900, 420),
            H("Jalur Utara", 32),
            P("Enam titik henti dari Danau Toba sampai Bukit Lawang, cocok untuk lima hari."),
            GAL(["wis1", "wis2", "wis3", "wis4", "wis5", "wis6"], 3, 12),
            BAR("nearbybar", thumb=pic("wis7", 160, 160), name="Warung Kopi Sidikalang",
                category="Kafe", distance="1,2 km", rating=4.5, open="open",
                open_note="Buka sampai 22.00", button="Rute"),
            BAR("routebar", start="Danau Toba", end="Bukit Lawang", duration="4 jam 20 menit",
                distance="186 km", button="Mulai"),
            BAR("linkbar", items="Itinerary|#\nPeta rute|#\nTitip pesan|#", align="center"),
            FOOT("Panduan wisata diperbarui Oktober 2026"),
        ]}],
    },
    "galeri_otomotif": {
        "name": "Galeri otomotif",
        "category": "Galeri",
        "desc": "Galeri kendaraan plus statistik performa, tabel spesifikasi, dan perbandingan.",
        "title": "Garasi Merah",
        "theme": theme_of("#dc2626", "#ffffff", "#111827", "Sans-serif modern", 840),
        "pages": [{"name": "Kendaraan", "elements": [
            BAR("appbar", title="Garasi Merah", subtitle="Galeri & spesifikasi", back="Kembali",
                action="Simpan", icon="bookmark"),
            GAL(["oto1", "oto2", "oto3", "oto4", "oto5", "oto6"], 3, 10),
            BAR("statsbar", items="204|Tenaga (hp)\n6,2 s|0-100 km/j\n240|Km/j top"),
            BAR("tablebar", columns="Mesin|40\nTransmisi|30\nTahun|30",
                row="2.0L Turbo|Otomatis 8 percepatan|2026"),
            BAR("comparebar", title="Perbandingan performa", items="Model ini|82\nGenerasi lalu|68",
                caption="Naik 14 poin dibanding generasi sebelumnya"),
            BAR("pricebar", price="Rp 512.000.000", caption="Harga on the road Jakarta",
                button="Minta penawaran", link="#"),
            FOOT("Foto hasil sesi studio internal, bukan materi iklan penjualan."),
        ]}],
    },
    "galeri_satwa": {
        "name": "Galeri satwa",
        "category": "Galeri",
        "desc": "Dokumentasi satwa dengan banner etika, siaran langsung, dan dukungan relawan.",
        "title": "Jejak Satwa",
        "theme": theme_of("#15803d", "#f7fee7", "#052e16", "Humanis", 800),
        "pages": [{"name": "Dokumentasi", "elements": [
            H("Jejak Satwa", 34),
            P("Dokumentasi burung dan mamalia kecil di kawasan konservasi seluas 1.200 hektar."),
            GAL(["sat1", "sat2", "sat3", "sat4", "sat5", "sat6"], 3, 18),
            BAR("infobanner", kind="warning", title="Jangan beri makan satwa liar",
                text="Pemberian makanan mengubah perilaku alami dan membahayakan mereka.",
                link_text="Panduan etika", link="#"),
            BAR("livebar", title="Siaran sarang elang", viewers="320 menonton", button="Tonton"),
            BAR("awardbar", badge="Sukarelawan Konservasi", note="Relawan sejak 2023",
                points="1.450 menit", icon="volunteer_activism", button="Dukung"),
            FOOT("Semua foto diambil dalam pengawasan pemandu resmi"),
        ]}],
    },
    "galeri_tanaman": {
        "name": "Galeri tanaman rumah",
        "category": "Galeri",
        "desc": "Galeri tanaman hias dengan kategori ikon, penilaian, dan progres gratis kirim.",
        "title": "Kebun Kecil",
        "theme": theme_of("#16a34a", "#f0fdf4", "#052e16", "Humanis", 780),
        "pages": [{"name": "Kebun", "elements": [
            H("Kebun Kecil", 32),
            P("Galeri tanaman rumah yang mudah dirawat, cocok untuk pemula."),
            BAR("categorybar", items="Daun|eco\nBerbunga|local_florist\nSukulen|yard\nHerbal|spa"),
            GAL(["tan1", "tan2", "tan3", "tan4", "tan5", "tan6"], 3, 14),
            BAR("ratinginputbar", label="Sudah pernah merawat tanaman ini?", value=4,
                low_label="Baru coba", high_label="Sudah jago"),
            BAR("productbar", image=pic("tan7", 160, 160), name="Monstera Deliciosa",
                note="Pot 20 cm · Tanah siap pakai", price="Rp 185.000", old_price="Rp 240.000", button="Tambah"),
            BAR("shippingbar", label="Belanja Rp 115.000 lagi untuk gratis kirim", value=52,
                min_label="Rp 0", max_label="Gratis kirim"),
            FOOT("Dikirim langsung dari kebun sendiri"),
        ]}],
    },
    "galeri_potret": {
        "name": "Galeri potret studio",
        "category": "Galeri",
        "desc": "Portofolio potret dengan jadwal sesi, jumlah orang, dan paket harga.",
        "title": "Studio Cahaya",
        "theme": theme_of("#a16207", "#fefce8", "#422006", "Sans-serif modern", 720),
        "pages": [{"name": "Portofolio", "elements": [
            H("Studio Cahaya", 32),
            P("Portofolio potret studio dan luar ruang, dikerjakan bersama satu asisten."),
            GAL(["por1", "por2", "por3", "por4", "por5", "por6"], 3, 22),
            BAR("datepickerbar", label="Pilih jadwal sesi", start="12 Okt 2026", end="12 Okt 2026",
                presets="Pagi\nSiang\nSore", active=1, button="Cek jadwal"),
            BAR("quantitybar", label="Jumlah orang", value=2,
                note="Tambahan orang dikenakan Rp 75.000", button="Lanjut"),
            BAR("pricebar", price="Rp 450.000", caption="Sesi 60 menit, 20 foto terpilih",
                button="Pesan sesi", link="#"),
            FOOT("Reschedule gratis maksimal 24 jam sebelum sesi"),
        ]}],
    },
    "galeri_konser": {
        "name": "Galeri konser",
        "category": "Galeri",
        "desc": "Galeri panggung dengan siaran langsung, hitung mundur, dan tiket.",
        "title": "Malam Bintang",
        "theme": theme_of("#7c3aed", "#0b1020", "#ede9fe", "Sans-serif modern", 800),
        "pages": [{"name": "Panggung", "elements": [
            BAR("appbar", title="Malam Bintang", subtitle="Galeri panggung 2026", back="Kembali",
                action="Bagikan", icon="share"),
            GAL(["kon1", "kon2", "kon3", "kon4", "kon5", "kon6"], 3, 12),
            BAR("livebar", title="Sedang berlangsung: sesi akustik", viewers="2.100 menonton", button="Tonton"),
            BAR("countdownbar", label="Pintu dibuka dalam", items="01|Jam\n15|Menit\n00|Detik"),
            BAR("orderbar", code="TIX-8891", status="pending", date="Dipesan 2 Okt",
                total="Rp 750.000", button="Bayar"),
            BAR("sharebar", label="Bagikan ke",
                items="Salin tautan|link\nInstagram|photo_camera\nX|tag"),
            FOOT("Galeri foto resmi panitia Malam Bintang"),
        ]}],
    },
    "galeri_olahraga": {
        "name": "Galeri olahraga",
        "category": "Galeri",
        "desc": "Galeri pertandingan dengan statistik tim, peringkat top skor, dan jadwal siaran.",
        "title": "Sorotan Lapangan",
        "theme": theme_of("#0369a1", "#ffffff", "#0c4a6e", "Sans-serif modern", 820),
        "pages": [{"name": "Pertandingan", "elements": [
            H("Sorotan Lapangan", 32),
            P("Galeri pertandingan dan statistik pemain liga daerah musim ini."),
            GAL(["ola1", "ola2", "ola3", "ola4", "ola5", "ola6"], 3, 10),
            BAR("statsbar", items="3|Gol\n12|Poin\n5|Menang"),
            BAR("rankingbar", title="Top skor sementara", unit="gol", items="Ardi|9\nBagas|7\nCakra|6"),
            BAR("livebar", title="Final pekan ini: Garuda vs Rajawali", viewers="860 menonton", button="Ingatkan"),
            BAR("pagination", pages=5, current=2),
            FOOT("Statistik diperbarui setiap pekan oleh panitia liga"),
        ]}],
    },
    "galeri_sejarah": {
        "name": "Galeri arsip sejarah",
        "category": "Galeri",
        "desc": "Koleksi foto arsip dengan lini masa restorasi dan catatan kurator.",
        "title": "Arsip Kota Tua",
        "theme": theme_of("#78350f", "#fffbeb", "#3f2d1a", "Serif klasik", 760),
        "pages": [{"name": "Arsip", "elements": [
            BAR("appbar", title="Arsip Kota Tua", subtitle="Koleksi 1900 sampai 1970", back="Beranda",
                action="Unduh", icon="download"),
            H("Jejak yang tersisa", 32),
            P("Foto arsip yang sudah direstorasi bersama keluarga pemilik aslinya."),
            GAL(["ars-arch1", "ars-arch2", "ars-arch3", "ars-arch4", "ars-arch5", "ars-arch6"], 3, 8),
            BAR("timelinebar", items="Arsip diterima|Jan\nRestorasi digital|Feb\nPublikasi|Okt", current=3),
            BAR("quotebar", text="Setiap foto adalah saksi yang tidak bisa bicara sendiri.",
                author="Tim Arsip", role="Kurator"),
            BAR("linkbar", items="Sumbang foto|#\nIzin penggunaan|#\nKontak kurator|#", align="center"),
            FOOT("Semua foto dipublikasikan dengan izin pemilik"),
        ]}],
    },
    "galeri_kerajinan": {
        "name": "Galeri kerajinan tangan",
        "category": "Galeri",
        "desc": "Galeri produk perajin lokal, cerita komunitas, dan tautan sosial.",
        "title": "Tangan Perajin",
        "theme": theme_of("#c2410c", "#fff7ed", "#431407", "Humanis", 780),
        "pages": [{"name": "Karya", "elements": [
            H("Tangan Perajin", 32),
            P("Galeri anyaman, batik tulis, dan keramik dari perajin lokal di 18 kota."),
            GAL(["kra1", "kra2", "kra3", "kra4", "kra5", "kra6"], 3, 14),
            BAR("productbar", image=pic("kra7", 160, 160), name="Keranjang Rotan Bulat",
                note="Diameter 30 cm · Rotan alam", price="Rp 165.000", old_price="", button="Tambah"),
            BAR("groupsbar", name="Komunitas Perajin Nusantara", members="1.240 perajin", avatar="",
                note="18 kota · aktif sejak 2019", button="Gabung"),
            BAR("socialbar", items="Instagram|#|photo_camera\nWhatsApp|#|chat\nKatalog|#|public"),
            FOOT("Dibuat tangan, bukan mesin"),
        ]}],
    },
    "galeri_interior": {
        "name": "Galeri desain interior",
        "category": "Galeri",
        "desc": "Galeri interior dengan palet warna, perbandingan sebelum-sesudah, dan estimasi.",
        "title": "Ruang yang Lapang",
        "theme": theme_of("#0f766e", "#f8fafc", "#134e4a", "Sans-serif modern", 860),
        "pages": [{"name": "Ruang", "elements": [
            H("Ruang yang Lapang", 32),
            P("Galeri sebelum-sesudah dan panduan palet warna ruangan keluarga."),
            GAL(["int1", "int2", "int3", "int4", "int5", "int6"], 3, 12),
            BAR("legendbar", title="Palet ruangan",
                items="Dinding|#f1f5f9\nKayu|#b98b5e\nAksen|#0f766e"),
            BAR("comparebar", title="Pencahayaan alami", items="Setelah renovasi|86\nSebelum renovasi|42",
                caption="Naik 44 poin setelah dinding dibuka"),
            BAR("pricebar", price="Rp 24.500.000", caption="Estimasi paket renovasi satu ruang",
                button="Konsultasi", link="#"),
            FOOT("Estimasi harga bisa berubah setelah survei lokasi"),
        ]}],
    },
    "galeri_properti": {
        "name": "Galeri properti",
        "category": "Galeri",
        "desc": "Galeri rumah dijual dengan pencarian, lokasi terdekat, dan simulasi DP.",
        "title": "Rumah Terang",
        "theme": theme_of("#1d4ed8", "#f8fafc", "#0f172a", "Sans-serif modern", 860),
        "pages": [{"name": "Unit", "elements": [
            BAR("appbar", title="Rumah Terang", subtitle="24 unit tersedia", back="Kembali",
                action="Simpan", icon="bookmark"),
            BAR("searchbar", placeholder="Cari lokasi atau tipe rumah", button="Cari"),
            GAL(["pro1", "pro2", "pro3", "pro4", "pro5", "pro6"], 3, 10),
            BAR("nearbybar", thumb=pic("pro7", 160, 160), name="Cluster Anggrek",
                category="Rumah tapak", distance="8 km dari pusat kota", rating=4.4, open="busy",
                open_note="22 orang melihat minggu ini", button="Jadwalkan"),
            BAR("savingsbar", title="Simulasi uang muka", value=35, collected="Rp 210 jt",
                target="Rp 600 jt", note="Estimasi tercapai empat tahun lagi", button="Tambah tabungan"),
            BAR("pricebar", price="Rp 1,45 M", caption="Tipe 60/120 · 3 kamar tidur",
                button="Ajukan KPR", link="#"),
            FOOT("Cicilan mulai Rp 8,9 juta per bulan"),
        ]}],
    },
    "galeri_astronomi": {
        "name": "Galeri astrofotografi",
        "category": "Galeri",
        "desc": "Galeri foto langit malam dengan prakiraan cuaca dan indikator polusi cahaya.",
        "title": "Langit Malam",
        "theme": theme_of("#4338ca", "#0b1020", "#e0e7ff", "Monospace", 820),
        "pages": [{"name": "Langit", "elements": [
            H("Langit Malam Nusantara", 32),
            P("Galeri astrofotografi dari delapan lokasi dengan polusi cahaya rendah."),
            GAL(["ast1", "ast2", "ast3", "ast4", "ast5", "ast6"], 3, 10),
            BAR("weatherbar", place="Observatorium Kupang", temp="22°C", note="Cerah penuh · Tanpa awan",
                icon="nightlight", high="24°", low="18°"),
            BAR("metricbar", label="Kelembapan udara", value="82%", delta="+6%", trend="up",
                status="warning", note="Ambang nyaman di bawah 70%"),
            BAR("legendbar", title="Keterangan",
                items="Galaksi|#a855f7\nNebula|#22d3ee\nBintang|#facc15"),
            FOOT("Waktu terbaik pengambilan foto: 21.00 sampai 03.00"),
        ]}],
    },
    "galeri_kampus": {
        "name": "Galeri kegiatan kampus",
        "category": "Galeri",
        "desc": "Galeri kegiatan mahasiswa dengan strip tanggal, absensi, dan tautan dokumen.",
        "title": "Kegiatan Kampus",
        "theme": theme_of("#1e40af", "#ffffff", "#1e1b4b", "Sans-serif modern", 840),
        "pages": [{"name": "Kegiatan", "elements": [
            BAR("appbar", title="Kegiatan Kampus", subtitle="Semester ganjil 2026/2027", back="Kembali",
                action="Tambah", icon="add"),
            H("Galeri kegiatan mahasiswa", 30),
            BAR("calendarstrip", items="Sen|12\nSel|13\nRab|14\nKam|15\nJum|16\nSab|17", active=3),
            GAL(["kam1", "kam2", "kam3", "kam4", "kam5", "kam6"], 3, 12),
            BAR("checkinbar", label="Absensi kegiatan", time="08:02",
                place="Gedung Serbaguna · Radius 50 m", status="in", button="Absen pulang"),
            BAR("linkbar", items="Kalender kegiatan|#\nUnduh dokumentasi|#\nHubungi panitia|#", align="center"),
            FOOT("Dokumentasi oleh Divisi Media Mahasiswa"),
        ]}],
    },
    "galeri_keluarga": {
        "name": "Galeri album keluarga",
        "category": "Galeri",
        "desc": "Album keluarga dengan pemilih periode, grup anggota, dan album terkait.",
        "title": "Album Keluarga",
        "theme": theme_of("#db2777", "#fff1f7", "#500724", "Humanis", 760),
        "pages": [{"name": "Album", "elements": [
            H("Album Keluarga Wibowo", 32),
            P("Kumpulan momen dari 2019 sampai hari ini, dirapikan per tahun."),
            GAL(["kel1", "kel2", "kel3", "kel4", "kel5", "kel6"], 3, 20),
            BAR("datepickerbar", label="Lihat album", start="Jan 2026", end="Okt 2026",
                presets="2026\n2025\nSemua", active=1, button="Buka album"),
            BAR("groupsbar", name="Grup Keluarga Wibowo", members="28 anggota", avatar="",
                note="12 unggahan baru bulan ini", button="Undang"),
            BAR("relatedbar", title="Album terkait",
                items="Liburan Bali 2024|42 foto\nWisuda Rani 2023|28 foto", button="Lihat semua"),
            FOOT("Album pribadi · hanya untuk anggota keluarga"),
        ]}],
    },
    "galeri_komponen_pro": {
        "name": "Galeri 50 komponen Pro",
        "category": "Referensi komponen",
        "desc": "Semua komponen paket Pro (navigasi, aksi, informasi, data, formulir, media, sosial, toko, keuangan, peta, konten) dalam empat halaman.",
        "title": "Galeri Komponen Pro",
        "theme": theme_of("#4f46e5", "#ffffff", "#1f2937", "Sans-serif modern", 780),
        "pages": [
            {"name": "Navigasi, Aksi & Informasi", "elements": [
                H("Navigasi", 24),
                BAR("appbar", title="Detail pesanan", subtitle="Diperbarui 5 menit lalu", back="Kembali",
                    action="Simpan", icon="more_vert"),
                BAR("quicknav", items="Isi ulang|add_card\nTransfer|swap_horiz\nScan|qr_code_scanner\nRiwayat|history", active=1),
                BAR("subnav", items="Ringkasan\nDetail\nUlasan\nRekomendasi", active=1),
                BAR("stepdots", total=5, current=2, label="Langkah 2 dari 5"),
                BAR("swipenav", label="Kartu 3 dari 8", prev="Sebelumnya", next="Berikutnya"),
                SPC(8),
                H("Aksi", 24),
                BAR("bulkactionbar", count=3, select_all="Pilih semua",
                    items="Hapus|delete\nPindah|drive_file_move\nArsip|archive"),
                BAR("exportbar", label="Ekspor data", formats="CSV\nExcel\nPDF", active=1, button="Unduh"),
                BAR("approvalbar", title="Permintaan cuti", note="Diajukan 2 jam lalu oleh Rani",
                    approve="Setujui", reject="Tolak"),
                BAR("printbar", label="Cetak dokumen", copies=2, size="A4", button="Cetak"),
                SPC(8),
                H("Informasi", 24),
                BAR("weatherbar", place="Jakarta", temp="31°C", note="Cerah berawan · Lembap 78%",
                    icon="wb_sunny", high="33°", low="26°"),
                BAR("notificationbar", app="Pesan", title="Kamu punya 3 pesan baru", time="09:12", unread="3"),
                BAR("metricbar", label="Waktu muat rata-rata", value="1,8 s", delta="+0,3 s", trend="up",
                    status="warning", note="Ambang batas 1,5 s"),
                BAR("updatebar", version="Versi 2.4.0", note="Perbaikan bug dan mode gelap baru",
                    size="18 MB", button="Perbarui"),
            ]},
            {"name": "Data & Formulir", "elements": [
                H("Data", 24),
                BAR("donutbar", label="Komposisi penjualan", caption="Total 1.240 pesanan",
                    items="Kopi|45|#6366f1\nMakanan|30|#f59e0b\nLainnya|25|#22c55e"),
                BAR("gaugebar", label="Kapasitas server", value=72, unit="%", min_label="0", max_label="100"),
                BAR("rankingbar", title="Produk terlaris", unit="terjual",
                    items="Kaos Katun Polos|182\nTote Bag Kanvas|140\nTopi Baseball|96"),
                BAR("heatmapbar", label="Kepadatan order per jam", caption="Puncak pukul 14.00",
                    values="0,1,2,3,5,8,12,15,11,7,4,2"),
                BAR("distributionbar", label="Distribusi jawaban", caption="n = 512 responden",
                    items="Sangat puas|48|#22c55e\nPuas|30|#3b82f6\nCukup|14|#f59e0b\nKurang|8|#ef4444"),
                BAR("funnelbar", label="Corong pendaftaran", caption="Konversi akhir 16%",
                    items="Kunjungan|100\nDaftar|42\nVerifikasi|28\nAktif|16"),
                SPC(8),
                H("Formulir", 24),
                BAR("uploadinputbar", label="Unggah dokumen pendukung", note="PDF atau JPG, maksimal 5 MB",
                    button="Pilih berkas", file="ktp.pdf", progress=60),
                BAR("datepickerbar", label="Periode laporan", start="01 Okt 2026", end="31 Okt 2026",
                    presets="7 hari\n30 hari\nKustom", active=2, button="Terapkan"),
                BAR("ratinginputbar", label="Seberapa puas kamu?", value=4,
                    low_label="Tidak puas", high_label="Sangat puas"),
                BAR("quantitybar", label="Jumlah", value=2, note="Maksimal 10 per pesanan", button="Tambah"),
                BAR("passstrengthbar", label="Kekuatan kata sandi", value=3,
                    levels="Lemah\nCukup\nKuat\nSangat kuat",
                    hints="Minimal 8 karakter\nKombinasi huruf besar & angka\nTambahkan simbol unik"),
            ]},
            {"name": "Media, Sosial & Toko", "elements": [
                H("Media", 24),
                BAR("videobar", thumb=pic("pro-video", 240, 140), title="Cara menyusun halaman",
                    channel="UI Builder", views="8,4 rb ditonton", duration="12:40", button="Putar"),
                BAR("equalizerbar", label="Equalizer", button="Reset",
                    items="60 Hz|4\n230 Hz|7\n910 Hz|2\n3 kHz|8\n14 kHz|5"),
                BAR("podcastbar", show="Sore Sore Podcast", episode="Ep. 42: Merancang untuk semua orang",
                    duration="38 menit", button="Putar"),
                BAR("camerabar", modes="Video\nFoto\nPotret\nMalam", active=2,
                    note="Geser untuk ganti mode", flash="flash_on"),
                BAR("lyricsbar", lines="Reff:\nMelangkah pelan di kota yang tak tidur\nMenghitung bintang dari balik jendela",
                    active=2, note="Sinkron otomatis"),
                SPC(8),
                H("Sosial", 24),
                BAR("groupsbar", name="Komunitas Desain Nusantara", members="2.840 anggota",
                    avatar="https://i.pravatar.cc/96?img=15", note="12 post baru minggu ini", button="Gabung"),
                BAR("trendbar", title="Sedang ramai",
                    items="#desainantarmuka|12,4 rb\n#buildwithstreamlit|8,1 rb\n#nusantaracreative|5,3 rb"),
                BAR("awardbar", badge="Pengguna Rajin", note="Login 30 hari berturut-turut",
                    points="+250 poin", icon="workspace_premium", button="Bagikan"),
                SPC(8),
                H("Toko", 24),
                BAR("wishlistbar", image=pic("pro-wish", 160, 160), name="Sepatu Lari Ringan",
                    price="Rp 429.000", note="Stok tersisa 4", button="Pindah ke keranjang"),
                BAR("orderbar", code="INV-2026-1042", status="shipped", date="Dikirim 4 Okt",
                    total="Rp 267.000", button="Lacak"),
                BAR("bundlingbar", title="Paket hemat sarapan", save="Hemat Rp 8.000", price="Rp 32.000",
                    items="Kopi Susu|Rp 22.000\nRoti Bakar|Rp 18.000", button="Ambil paket"),
                BAR("loyaltybar", level="Level Gold", points="1.240 poin", value=68,
                    next="480 poin lagi ke Platinum", button="Tukar poin"),
            ]},
            {"name": "Keuangan, Peta & Konten", "elements": [
                H("Keuangan", 24),
                BAR("balancebar", label="Saldo tersedia", amount="Rp 3.450.000", note="Diperbarui 08:12",
                    button="Isi ulang", icon="account_balance_wallet"),
                BAR("transactionbar", title="Transfer ke Budi", time="Hari ini, 09:24",
                    amount="- Rp 150.000", kind="out", category="Transfer", button="Detail", icon="swap_vert"),
                BAR("budgetbar", label="Anggaran bulanan", spent="Rp 2,4 jt", total="Rp 4 jt", value=60,
                    status="safe", note="Sisa Rp 1,6 juta untuk 12 hari"),
                BAR("invoicebar", title="Tagihan listrik", due="Jatuh tempo 20 Okt", amount="Rp 412.500",
                    status="due", button="Bayar"),
                BAR("savingsbar", title="Liburan ke Jepang", value=45, collected="Rp 18 jt",
                    target="Rp 40 jt", note="Estimasi tercapai Jun 2027", button="Tambah dana"),
                SPC(8),
                H("Peta & Lokasi", 24),
                BAR("locationbar", label="Lokasi saat ini", place="Jl. Sudirman No. 12, Jakarta",
                    accuracy="Akurasi 12 m", button="Ubah", thumb=""),
                BAR("routebar", start="Kantor", end="Bandara Soekarno-Hatta", duration="48 menit",
                    distance="24,6 km", button="Mulai"),
                BAR("nearbybar", thumb=pic("pro-nearby", 160, 160), name="Kopi Sudut", category="Kafe",
                    distance="350 m", rating=4.6, open="open", open_note="Buka sampai 22.00", button="Rute"),
                BAR("checkinbar", label="Absen masuk", time="08:02", place="Kantor Pusat · Radius 50 m",
                    status="in", button="Absen pulang"),
                SPC(8),
                H("Konten", 24),
                BAR("articlebar", category="Panduan", title="Merancang tata letak yang mudah dibaca",
                    meta="7 menit baca · 4 Okt 2026", button="Baca"),
                BAR("authorbar", name="Sari Wulandari", role="Penulis & Peneliti UX", avatar="",
                    posts="48 tulisan", button="Ikuti"),
                BAR("chaptersbar", title="Bab 3: Warna dan Kontras",
                    items="3.1 Teori warna\n3.2 Kontras teks\n3.3 Latihan mandiri\n3.4 Ringkasan",
                    current=3, progress=60),
                BAR("readingprogressbar", label="Halaman 12 dari 28", value=43, note="Sisa 16 menit",
                    button="Lanjut baca"),
                BAR("relatedbar", title="Bacaan terkait",
                    items="Tipografi untuk pemula|6 menit\nMenata grid 12 kolom|9 menit", button="Lihat semua"),
            ]},
        ],
    },
}


def template_design(key):
    """Buat salinan desain dari template, lengkap dengan id baru."""
    tpl = copy.deepcopy(TEMPLATES[key])
    theme = default_design()["theme"]
    theme.update(tpl["theme"])
    pages = tpl["pages"]
    for page in pages:
        page["id"] = uuid.uuid4().hex[:8]
        for el in page["elements"]:
            el["id"] = uuid.uuid4().hex[:8]
    return {"title": tpl["title"], "theme": theme, "pages": pages}
